trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
      - .gitignore
      - README.md
pr: none
pool:
  vmImage: 'ubuntu-latest'
name: 2.0$(Rev:.r)
variables:
  - group: 'NuGetPublishing'
steps:
- task: NuGetToolInstaller@1
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
- task: DotNetCoreCLI@2
  displayName: 'Package'
  inputs:
    command: 'pack'
    packagesToPack: '**/Emmersion.EventLogWalker.csproj'
    versioningScheme: 'byBuildNumber'
- task: NuGetCommand@2
  displayName: 'Publish to internal feed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '2ee1cde5-9787-4e91-b498-e30a43c5d914'
